# Generated by Django 3.1 on 2020-11-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='fine/imges'),
        ),
    ]
