# Generated by Django 3.1 on 2020-11-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=111)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
